import type { NextPage } from 'next';
import Head from 'next/head';
import { Heading, Text } from '@chakra-ui/react';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Heading>Hello world</Heading>
      <Text color="orange.600" fontWeight={700}>
        こんにちは
      </Text>
    </>
  );
};

export default Home;
